app/models.py
from . import mongo

class Person_Meizi(mongo.Document):
    edu = mongo.StringField()
    pic_logo = mongo.StringField()
    height = mongo.StringField()
    NickName = mongo.StringField()
    work_location = mongo.StringField()
    zodiac = mongo.StringField()
    vocation = mongo.StringField()
    marry_status = mongo.StringField()
    salary = mongo.StringField()
    MemberId = mongo.StringField()
    age = mongo.StringField()
    hometown_location = mongo.StringField()

    meta = {'collection': 'zhenaidatabase'}

app/main/forms.py
from  flask_wtf import Form
from .. import mongo

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mongoengine import MongoEngine
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()
mongo = MongoEngine()
login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    mongo.init_app(app)
    login_manager.init_app(app)
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for, current_app, abort, flash, request, make_response
from . import main
from .. import db
from .. import config
from ..models import Person_Meizi

@main.route('/', methods=['GET', 'POST'])
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Person_Meizi.objects.paginate(page=page, per_page=current_app.config["FLASK_IMAGES_PER_PAGE"])
    imgs = pagination.items
    return render_template('index.html', imgs=imgs, pagination=pagination)

@main.route('/map', methods=['GET', 'POST'])
def map():
    meizi_list = list(Person_Meizi.objects.all())
    location_list = []
    map_val = {}
    for meizi in meizi_list:
        if meizi.work_location not in location_list:
            location_list.append(meizi.work_location)
            map_val[meizi.work_location]=1
        else:
            map_val[meizi.work_location]+=1
    return_val = []

    for key in map_val.keys():
        new_map = {}
        new_map['name'] = key.replace("北京","")
        new_map['value'] = map_val[key]
        return_val.append(new_map)
    return render_template('index_map.html', map_val=map_val, return_val=return_val)

@main.route('/data_detail', methods=['GET'])
def data_detail():
    return render_template('index_data_detail.html')

@main.route('/get_data/<data_type>', methods=['POST'])
def get_data(data_type):
    meizi_list = list(Person_Meizi.objects.all().order_by(data_type))
    type_list =  []
    type_val = {}
    if data_type == 'age':
        for meizi in meizi_list:
            if meizi.age not in type_list:
                type_list.append(meizi.age)
                type_val[meizi.age]=1
            else:
                type_val[meizi.age]+=1
    elif data_type =='edu':
        for meizi in meizi_list:
            if meizi.edu not in type_list:
                type_list.append(meizi.edu)
                type_val[meizi.edu]=1
            else:
                type_val[meizi.edu]+=1
    elif data_type =='height':
        for meizi in meizi_list:
            if meizi.height not in type_list:
                type_list.append(meizi.height)
                type_val[meizi.height]=1
            else:
                type_val[meizi.height]+=1
    elif data_type == 'marry_status' :
        for meizi in meizi_list:
            if meizi.marry_status not in type_list:
                type_list.append(meizi.marry_status)
                type_val[meizi.marry_status]=1
            else:
                type_val[meizi.marry_status]+=1

    return_val = []
    if data_type == "height" or data_type == "age":
        for type_item in type_list:
            return_val.append(type_val[type_item])
    else :
        for key in type_val.keys():
            new_map = {}
            new_map['name'] = key
            new_map['value'] = type_val[key]
            return_val.append(new_map)

    if data_type == "height" or data_type == "age":
        return str(type_list)+'^'+str(return_val)
    else :
        return str(list(type_val.keys()))+'^'+ str(return_val)

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
        <a href="{% if pagination.has_prev %}
            {{ url_for(endpoint, page=pagination.page-1, **kwargs) }}
            {% else %}
            #{% endif %}" >
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p%}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
               <a href="{{ url_for(endpoint, page=p, **kwargs)}}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li {% if not pagination.has_next %} class="disabled" {% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/base.html
{% extends "bootstrap/base.html"  %}
{% block title%}珍爱妹子{% endblock %}
{% block head %}
{{super()}}
<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
<link rel="stylesheet" type="text/css" href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css')  }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='img_list.css')  }}">
<link rel="stylesheet" type="text/css" href="http://cdn.bootcss.com/pace/1.0.2/themes/black/pace-theme-barber-shop.min.css">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
 <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">珍爱妹子</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{{url_for('main.index')}}">首页</a></li>
            <li><a href="{{ url_for('main.map') }}">珍爱地图</a></li>
            <li><a href="{{ url_for('main.data_detail') }}">珍爱数据</a></li>
          </ul>
        </div>
      </div>
      </div>
{% endblock %}
{% block content %}
<div class="container">
{% for message in get_flashed_messages() %}
    <div class="alert alert-warning" >
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

{% block page_content %}
{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="http://cdn.bootcss.com/pace/1.0.2/pace.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='zooming.js')}}"></script>
<script type="text/javascript">
  $(function(){


  })
</script>
{% endblock%}

app/templates/img_list.html
<section id="gallery-wrapper">
    {% for img in imgs %}
    <article class="white-panel">
        <a href="http://album.zhenai.com/u/{{ img.MemberId }}?flag=s" target="_blank">
        <img src="{{ img.pic_logo.split('_')[0]+'_2.jpg' }}" class="thumb" data-action='zoom' alt="{{ img.salary }}">
        <h1>{{ img.NickName }}</h1>
        </a>
        {% if img.height.replace("CM", "")|int > 165 %}
        <span class="label label-info">高挑</span>
        {% endif %}
        {% if img.age.replace("岁", "")|int < 25%}
        <span class="label label-warning">情窦初开</span>
        {% elif img.age.replace("岁", "")|int < 30 %}
        <span class="label label-warning">温暖柔情</span>
        {% else %}
        <span class="label label-warning">成熟大方</span>
        {% endif %}
        {% if img.edu == "硕士" or img.edu =="博士" %}
        <span class="label label-success">高智商</span>
        {% endif %}
        <span class="label label-primary">{{ img.salary }}</span>

    </article>
    {% endfor %}
</section>

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}珍爱妹子们{% endblock%}

{% block page_content %}
<div class="row row-offcanvas row-offcanvas-right">
<div class="col-xs-12 col-sm-9 col-md-offset-1">
<p class="pull-right visible-xs">
    <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">显示标签</button>
</p>
<div class="row">
{% include "img_list.html" %}

{% if pagination %}
<div class="pagination" style="align-self: center;">
    {{ macros.pagination_widget(pagination, '.index') }}
</div>
{% endif %}
</div>
</div>
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='pinterest_grid.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="offcanvas"]').click(function(){
        $('.row-offcanvas').toggleClass('active')
    })
    $("#gallery-wrapper").pinterest_grid();
})
</script>
{% endblock %}

app/templates/index_data_detail.html
{% extends "base.html" %}

{% block title %}珍爱数据可视化{% endblock%}

{% block navbar %}
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
 <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">珍爱妹子</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li ><a href="{{url_for('main.index')}}">首页</a></li>
            <li><a href="{{ url_for('main.map') }}">珍爱地图</a></li>
            <li  class="active"><a href="{{ url_for('main.data_detail') }}">珍爱数据</a></li>
          </ul>
        </div>
      </div>
      </div>
{% endblock %}
{% block page_content %}
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-offset-3">
            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
            <button type="button" class="btn btn-primary btn-data" value="age" onclick="ShowDataDetail('age')">查看年龄细分布</button>

            <!-- Indicates a successful or positive action -->
            <button type="button" class="btn btn-success btn-data" value="height" onclick="ShowDataDetail('height')">查看身高细分布</button>

            <!-- Contextual button for informational alert messages -->
            <button type="button" class="btn btn-info btn-data" value="edu" onclick="ShowDataDetail('edu')" >查看学历细分布</button>

            <button type="button" class="btn btn-danger btn-data" valuue="marry_statu" onclick="ShowDataDetail('marry_status')" >查看婚姻细分布</button>

            <div id="main" style="width:600px;height:500px;">

            </div>
        </div>

    </div>
{% endblock %}
{% block scripts %}
{{  super() }}
<script src="{{ url_for('static', filename='echarts.js') }}" charset="utf-8"></script>
<script type="text/javascript">
$(function(){
    ShowDataDetail('age')
})
function ShowDataDetail(type){
    var myChart = echarts.init(document.getElementById('main'));
    myChart.showLoading();
    $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    var return_val = "";
    $.ajax({
        type:'post',
        url: $SCRIPT_ROOT+'/get_data/'+type,
        async: false,
        success:function(data){
            return_val = data
            myChart.hideLoading();
        },
        error:function(){}

    })
    col_list = return_val.split('^')[0]
    val_list = return_val.split('^')[1]
if (type =="age" || type =="height") {

    option ={
        title: {
            text: '珍爱妹子详细数据分布',
            left: 'center',
            top: 20,
            textStyle: {
                color: '#ccc'
            }
        },
        tooltip : {
            trigger: 'axis',
            axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
            }
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        xAxis : [
            {
                type : 'category',
                data : eval(col_list),
                axisTick: {
                    alignWithLabel: true
                }
            }
        ],
        yAxis : [
            {
                type : 'value'
            }
        ],
        series : [
            {
                type:'bar',
                barWidth: '60%',
                data:eval(val_list)
            }
        ]
    };
}
else {
    var val_title=""
    if (type=="edu") {
        val_title = "教育程度"
    }
    else {
            val_title = "婚姻状况"
    }
    option = {
        title : {
                text: '珍爱妹子详细数据分布',
                x:'center'
            },
            tooltip : {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                orient: 'vertical',
                left: 'left',
                data: eval(col_list)
            },
            series : [
                {
                    name: val_title,
                    type: 'pie',
                    radius : '55%',
                    center: ['50%', '60%'],
                    data:eval(val_list),
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }
            ]

};
}
// 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
}
</script>
{% endblock %}

app/templates/index_map.html
{% extends "base.html" %}

{% block title %}珍爱地图{% endblock%}

{% block navbar %}
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
 <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">珍爱妹子</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li ><a href="{{url_for('main.index')}}">首页</a></li>
            <li class="active"><a href="{{ url_for('main.map') }}">珍爱地图</a></li>
            <li><a href="{{ url_for('main.data_detail') }}">珍爱数据</a></li>
          </ul>
        </div>
      </div>
      </div>
{% endblock %}

{% block page_content %}
<div class="row">
    <div class="col-xs-12 col-sm-9 col-md-offset-2">
        <input type="hidden" name="" value="{{ map_val }}">
        <input type="hidden" name="" value="{{ return_val }}" id="hidMapVal">
        <div id="main" style="width:600px;height:600px;">

        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='echarts.js') }}" charset="utf-8"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="offcanvas"]').click(function(){
        $('.row-offcanvas').toggleClass('active')
    })
    var myChart = echarts.init(document.getElementById('main'));
    myChart.showLoading();
 var dataArray =eval($('#hidMapVal').val())
$.get('{{ url_for("static", filename="beijing.json")}}', function (geoJson) {

    myChart.hideLoading();

    echarts.registerMap('beijing', geoJson);

    myChart.setOption(option = {
        title: {
            text: '珍爱北京妹子分布图',
            subtext: '数据来自珍爱网',
            sublink: 'http://search.zhenai.com/v2/search/pinterest.do'
        },
        tooltip: {
            trigger: 'item',
            formatter: '{b}<br/>共{c}人'
        },
        toolbox: {
            show: true,
            orient: 'vertical',
            left: 'right',
            top: 'center',
            feature: {
                dataView: {readOnly: false},
                restore: {},
                saveAsImage: {}
            }
        },
        visualMap: {
            min: 0,
            max: 600,
            text:['High','Low'],
            realtime: false,
            calculable: true,
            inRange: {
                color: ['lightskyblue','yellow', 'orangered']
            }
        },
        series: [
            {
                name: '珍爱北京妹子分布图',
                type: 'map',
                mapType: 'beijing', // 自定义扩展图表类型
                itemStyle:{
                    emphasis:{label:{show:true}}
                },
                data:dataArray,
                // 自定义名称映射

            }
        ]
    });
});
})
</script>
{% endblock %}